### ISSUE TITLE
User Attributes not saving.

### ISSUE THREAD

**Issue by torodavit** [infobip/mobile-messaging-sdk-ios#19] opened 2020-05-06 06:51 UTC
# Please fill out the following form to help us to resolve you issue faster.

* MobileMessaging SDK version: 7.0.3
* Xcode version: 11.4.1
* Your application language: Swift 5
* Cocoapods version: 1.9.0

I personalize user info this is code.
![Screen Shot 2020-05-06 at 10 45 20](https://user-images.githubusercontent.com/5978296/81145136-b9928b80-8f86-11ea-9f65-f6afdb4bcc46.png)

error not happening

This is screen shot from portal

![Screen Shot 2020-05-06 at 10 50 22](https://user-images.githubusercontent.com/5978296/81145494-6ec54380-8f87-11ea-8e54-4de4e67ccf67.png)

not save info

**Comment by kas-kad** [comment] 2020-05-06 08:18
Hello, thanks for the report, I'll get back to you with more info.

**Comment by kas-kad** [comment] 2020-05-12 10:23
Hello, did you try using `MobileMessaging.personalize(**forceDepersonalize: true**, userIdentity: userAttributes: completion:)`? It is usually more preferable way to personalize installation.

**Comment by kas-kad** [comment] 2020-05-12 17:58
We've found the reason for the wrong "personalize" behaviour. We'll let you know when it's fixed.

**Comment by torodavit** [comment] 2020-05-13 07:49
Hello, I dig in code. I tried personalize with flag forceDepersonalize but nothing. 
When i call method MobileMessaging.personalize 
Request is 
```
(lldb) po request
2020-05-13 11:40:36.358636+0400 PickUP[6503:1489697] CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    ptcl = htps;
    "r_Attributes" = 1;
    sdmn = "mobile.infobip.com";
    srvr = "mobile.infobip.com";
    sync = syna;
}
$ curl -v \
	-X POST \
	-H "Accept: application/json" \
	-H "User-Agent: org.cocoapods.MobileMessaging/8.0.0(iOS;13.4.1;;iPhone XS;;com.lemondo.PickUP;1.0;Tornike Davitashvili’s iPhone;GEOCELL;01;282)" \
	-H "Content-Type: application/json" \
	-H "Authorization: App 6958ba1a378612a3a62399d6fc789b34-dd6e7f85-2961-4b4e-bca2-d9c9abdf459f" \
	-H "pushregistrationid: 6cd68d52-f58c-42ad-bca5-2f5b5a5f4195" \
	-H "applicationcode: 9d435a65a2" \
	-H "sessionId: 6cd68d52-f58c-42ad-bca5-2f5b5a5f4195_1589355618196" \
	-H "installationid: F7269270-924C-4A5B-BE02-2AC779993E22" \
	-H "foreground: true" \
	-d "{\"userIdentity\":{\"externalUserId\":\"pickup_3\"},\"userAttributes\":{\"birthday\":\"2000-03-31\",\"lastName\":\"tornikegg\",\"firstName\":\"tornikegg\",\"customAttributes\":{\"ExternalUserId\":\"pickup_3\"}}}" \
	"https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1"
```
and callback is 

`(lldb) po dataResult
▿ [Request]: POST https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1
[Response]: <NSHTTPURLResponse: 0x283359340> { URL: https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1 } { Status Code: 200, Headers {
    "Content-Length" =     (
        544
    );
    "Content-Type" =     (
        "application/json;charset=utf-8"
    );
    Date =     (
        "Wed, 13 May 2020 07:42:59 GMT"
    );
    Server =     (
        "SMS API"
    );
} }
[Data]: 544 bytes
[Result]: SUCCESS: 544 bytes
[Timeline]: Timeline: { "Request Start Time": 611048579.007, "Initial Response Time": 611048579.399, "Request Completed Time": 611048579.400, "Serialization Completed Time": 611048579.401, "Latency": 0.393 secs, "Request Duration": 0.394 secs, "Serialization Duration": 0.000 secs, "Total Duration": 0.394 secs }
  ▿ request : Optional<URLRequest>
    ▿ some : https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1
      ▿ url : Optional<URL>
        ▿ some : https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1
          - _url : https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1
      - cachePolicy : 0
      - timeoutInterval : 60.0
      - mainDocumentURL : nil
      - networkServiceType : __C.NSURLRequestNetworkServiceType
      - allowsCellularAccess : true
      ▿ httpMethod : Optional<String>
        - some : "POST"
      ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
        ▿ some : 9 elements
          ▿ 0 : 2 elements
            - key : "applicationcode"
            - value : "9d435a65a2"
          ▿ 1 : 2 elements
            - key : "foreground"
            - value : "true"
          ▿ 2 : 2 elements
            - key : "installationid"
            - value : "F7269270-924C-4A5B-BE02-2AC779993E22"
          ▿ 3 : 2 elements
            - key : "Accept"
            - value : "application/json"
          ▿ 4 : 2 elements
            - key : "Authorization"
            - value : "App 6958ba1a378612a3a62399d6fc789b34-dd6e7f85-2961-4b4e-bca2-d9c9abdf459f"
          ▿ 5 : 2 elements
            - key : "sessionId"
            - value : "6cd68d52-f58c-42ad-bca5-2f5b5a5f4195_1589355731192"
          ▿ 6 : 2 elements
            - key : "User-Agent"
            - value : "org.cocoapods.MobileMessaging/8.0.0(iOS;13.4.1;;iPhone XS;;com.lemondo.PickUP;1.0;Tornike Davitashvili’s iPhone;GEOCELL;01;282)"
          ▿ 7 : 2 elements
            - key : "Content-Type"
            - value : "application/json"
          ▿ 8 : 2 elements
            - key : "pushregistrationid"
            - value : "6cd68d52-f58c-42ad-bca5-2f5b5a5f4195"
      ▿ httpBody : Optional<Data>
        ▿ some : 185 bytes
          - count : 185
          ▿ pointer : 0x00000002806c09c0
            - pointerValue : 10744498624
      - httpBodyStream : nil
      - httpShouldHandleCookies : true
      - httpShouldUsePipelining : false
  ▿ response : Optional<NSHTTPURLResponse>
    - some : <NSHTTPURLResponse: 0x283359340> { URL: https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1 } { Status Code: 200, Headers {
    "Content-Length" =     (
        544
    );
    "Content-Type" =     (
        "application/json;charset=utf-8"
    );
    Date =     (
        "Wed, 13 May 2020 07:42:59 GMT"
    );
    Server =     (
        "SMS API"
    );
} }
  ▿ data : Optional<Data>
    ▿ some : 544 bytes
      - count : 544
      ▿ pointer : 0x000000012ff56350
        - pointerValue : 5099578192
  ▿ result : SUCCESS: 544 bytes
    ▿ success : 544 bytes
      - count : 544
      ▿ pointer : 0x000000012ff56350
        - pointerValue : 5099578192
  ▿ timeline : Timeline: { "Request Start Time": 611048579.007, "Initial Response Time": 611048579.399, "Request Completed Time": 611048579.400, "Serialization Completed Time": 611048579.401, "Latency": 0.393 secs, "Request Duration": 0.394 secs, "Serialization Duration": 0.000 secs, "Total Duration": 0.394 secs }
    - requestStartTime : 611048579.006544
    - initialResponseTime : 611048579.399339
    - requestCompletedTime : 611048579.400216
    - serializationCompletedTime : 611048579.400593
    - latency : 0.39279496669769287
    - requestDuration : 0.39367198944091797
    - serializationDuration : 0.0003770589828491211
    - totalDuration : 0.3940490484237671
  ▿ _metrics : Optional<AnyObject>
    - some : (Task Interval) <_NSConcreteDateInterval: 0x2833eee60> (Start Date) 2020-05-13 07:42:59 +0000 + (Duration) 0.392824 seconds = (End Date) 2020-05-13 07:42:59 +0000
(Redirect Count) 0
(Transaction Metrics) (Request) <NSMutableURLRequest: 0x2831fcfc0> { URL: https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1 }
(Response) <NSHTTPURLResponse: 0x2833a9960> { URL: https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1 } { Status Code: 200, Headers {
    "Content-Length" =     (
        544
    );
    "Content-Type" =     (
        "application/json;charset=utf-8"
    );
    Date =     (
        "Wed, 13 May 2020 07:08:03 GMT"
    );
    Server =     (
        "SMS API"
    );
} }
(Fetch Start) 2020-05-13 07:42:59 +0000
(Domain Lookup Start) (null)
(Domain Lookup End) (null)
(Connect Start) (null)
(Secure Connection Start) (null)
(Secure Connection End) (null)
(Connect End) (null)
(Request Start) 2020-05-13 07:42:59 +0000
(Request End) 2020-05-13 07:42:59 +0000
(Response Start) 2020-05-13 07:42:59 +0000
(Response End) 2020-05-13 07:42:59 +0000
(Protocol Name) (null)
(Proxy Connection) NO
(Reused Connection) NO
(Fetch Type) Local Cache
(Request Header Bytes) 0
(Request Body Transfer Bytes) 0
(Request Body Bytes) 0
(Response Header Bytes) 0
(Response Body Transfer Bytes) 0
(Response Body Bytes) 0
(Local Address) (null)
(Local Port) (null)
(Remote Address) (null)
(Remote Port) (null)
(TLS Protocol Version) 0x0000
(TLS Cipher Suite) 0x0000
(Cellular) NO
(Expensive) NO
(Constrained) NO
(Multipath) NO

(Request) <NSURLRequest: 0x2831fd640> { URL: https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1 }
(Response) <NSHTTPURLResponse: 0x2833aaf00> { URL: https://mobile.infobip.com/mobile/1/appinstance/6cd68d52-f58c-42ad-bca5-2f5b5a5f4195/personalize?forceDepersonalize=1 } { Status Code: 200, Headers {
    "Content-Length" =     (
        544
    );
    "Content-Type" =     (
        "application/json;charset=utf-8"
    );
    Date =     (
        "Wed, 13 May 2020 07:42:59 GMT"
    );
    Server =     (
        "SMS API"
    );
} }
(Fetch Start) 2020-05-13 07:42:59 +0000
(Domain Lookup Start) 2020-05-13 07:42:59 +0000
(Domain Lookup End) 2020-05-13 07:42:59 +0000
(Connect Start) 2020-05-13 07:42:59 +0000
(Secure Connection Start) 2020-05-13 07:42:59 +0000
(Secure Connection End) 2020-05-13 07:42:59 +0000
(Connect End) 2020-05-13 07:42:59 +0000
(Request Start) 2020-05-13 07:42:59 +0000
(Request End) 2020-05-13 07:42:59 +0000
(Response Start) 2020-05-13 07:42:59 +0000
(Response End) 2020-05-13 07:42:59 +0000
(Protocol Name) http/1.1
(Proxy Connection) NO
(Reused Connection) NO
(Fetch Type) Network Load
(Request Header Bytes) 726
(Request Body Transfer Bytes) 185
(Request Body Bytes) 185
(Response Header Bytes) 138
(Response Body Transfer Bytes) 544
(Response Body Bytes) 544
(Local Address) 192.168.0.102
(Local Port) 57674
(Remote Address) 3.123.239.72
(Remote Port) 443
(TLS Protocol Version) 0x0303
(TLS Cipher Suite) 0xC02F
(Cellular) NO
(Expensive) NO
(Constrained) NO
(Multipath) NO`

and his data JSON is 

`(lldb) po responseJson
▿ {
  "customAttributes" : {
    "ExternalUserId" : "pickup_3"
  },
  "birthday" : "2000-03-31",
  "instances" : [
    {
      "isPrimary" : false,
      "notificationsEnabled" : true,
      "osVersion" : "13.4.1",
      "pushRegId" : "6cd68d52-f58c-42ad-bca5-2f5b5a5f4195",
      "regEnabled" : true,
      "deviceModel" : "iPhone XS",
      "deviceName" : "Tornike Davitashvili’s iPhone",
      "os" : "iOS",
      "language" : "en",
      "geoEnabled" : false,
      "deviceTimezoneOffset" : "GMT+04:00",
      "deviceManufacturer" : "Apple",
      "sdkVersion" : "8.0.0",
      "appVersion" : "1.0",
      "deviceSecure" : true
    }
  ],
  "firstName" : "tornikegg",
  "externalUserId" : "pickup_3",
  "lastName" : "tornikegg"
}
  - rawArray : 0 elements
  ▿ rawDictionary : 6 elements
    ▿ 0 : 2 elements
      - key : "customAttributes"
      ▿ value : 1 element
        ▿ 0 : 2 elements
          - key : ExternalUserId
          - value : pickup_3
    ▿ 1 : 2 elements
      - key : "birthday"
      - value : 2000-03-31
    ▿ 2 : 2 elements
      - key : "instances"
      ▿ value : 1 element
        ▿ 0 : 15 elements
          ▿ 0 : 2 elements
            - key : isPrimary
            - value : 0
          ▿ 1 : 2 elements
            - key : notificationsEnabled
            - value : 1
          ▿ 2 : 2 elements
            - key : osVersion
            - value : 13.4.1
          ▿ 3 : 2 elements
            - key : pushRegId
            - value : 6cd68d52-f58c-42ad-bca5-2f5b5a5f4195
          ▿ 4 : 2 elements
            - key : regEnabled
            - value : 1
          ▿ 5 : 2 elements
            - key : deviceModel
            - value : iPhone XS
          ▿ 6 : 2 elements
            - key : deviceName
            - value : Tornike Davitashvili’s iPhone
          ▿ 7 : 2 elements
            - key : os
            - value : iOS
          ▿ 8 : 2 elements
            - key : language
            - value : en
          ▿ 9 : 2 elements
            - key : geoEnabled
            - value : 0
          ▿ 10 : 2 elements
            - key : deviceTimezoneOffset
            - value : GMT+04:00
          ▿ 11 : 2 elements
            - key : deviceManufacturer
            - value : Apple
          ▿ 12 : 2 elements
            - key : sdkVersion
            - value : 8.0.0
          ▿ 13 : 2 elements
            - key : appVersion
            - value : 1.0
          ▿ 14 : 2 elements
            - key : deviceSecure
            - value : 1
    ▿ 3 : 2 elements
      - key : "firstName"
      - value : tornikegg
    ▿ 4 : 2 elements
      - key : "externalUserId"
      - value : pickup_3
    ▿ 5 : 2 elements
      - key : "lastName"
      - value : tornikegg
  - rawString : ""
  - rawNumber : 0
  - rawNull : <null>
  - rawBool : false
  - _type : MobileMessaging.Type.dictionary
  - _error : nil

(lldb)`

This log may help find

**Comment by kas-kad** [comment] 2020-05-13 08:33
@torodavit I've hidden your last comment because it discovers sensitive information such as your application code (API key).

**Comment by kas-kad** [comment] 2020-05-13 08:37
@torodavit since your last comment has discovered potentially sensitive information (Application Code/API key) please consider migrating to a new Push Application (create and setup a new application on our Portal).

**Comment by kas-kad** [comment] 2020-05-13 08:48
@torodavit regarding the issue, we are going to fix it by the end of this week. I'll keep you updated.

**Comment by kas-kad** [comment] 2020-05-18 09:12
@torodavit Hello. The fix has been deployed recently, let me know whether the issue is still relevant or not.

**Comment by torodavit** [comment] 2020-05-19 09:51
@kas-kad  Hello. I test it and it's work <3 
Thanks a lot ^__^

**Closed** 2020-05-19 09:57 UTC
